# Generated by Django 5.1 on 2024-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_alter_codesubmission_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(blank=True, choices=[('py', 'Python'), ('c', 'C'), ('cpp', 'C++'), ('js', 'Javascript')], max_length=10, null=True),
        ),
    ]
